#!/usr/bin/env bash
set -e

KUSTOMIZE_DIRS=$(find . -type f -name '*kustomization.yaml' | sed -E 's|/[^/]+$||' |sort -u )
COLOR_GREEN="\x1b[32;01m"
COLOR_YELLOW="\x1b[33;01m"
COLOR_RED="\x1b[31;01m"
COLOR_RESET="\x1b[39;49;00m"

FAILED=0
IFS=$'\n'
echo "test: kustomize build"
for item in $KUSTOMIZE_DIRS
do
  echo -e $COLOR_YELLOW"[START] kustomize build $item"$COLOR_RESET
  item_failed=0
  CMD_OUT=$(kustomize build $item) || item_failed=1
  if [ $item_failed = "1" ]; then
    FAILED=1
    echo -e $COLOR_RED"$CMD_OUT"$COLOR_RESET
    echo -e $COLOR_RED"[FAILED] kustomize build $item"$COLOR_RESET
  else
    echo -e $COLOR_GREEN"[PASS]  kustomize build $item"$COLOR_RESET
  fi
done

exit $FAILED
