repos:
  - repo: https://github.com/prettier/prettier
    rev: "2.0.5"
    hooks:
      - id: prettier
        language_version: system
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        language_version: system
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
