name: CI

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pre-commit
        uses: open-turo/action-pre-commit@v1
      - name: Check release notes on pull_request
        if: github.event_name == 'pull_request'
        uses: open-turo/actions-release/lint-release-notes@v4

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo no tests
        shell: bash
