name: CI

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches-ignore:
      - main

jobs:

  release-notes:
    name: Release notes preview
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-release/lint-release-notes@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: open-turo/action-pre-commit@v1

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo no tests
        shell: bash
