name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:

  release-notes:
    name: Release notes preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: open-turo/actions-release/lint-release-notes@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NPM_TOKEN: ${{ secrets.OPEN_TURO_NPM_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: open-turo/action-pre-commit@v3

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo no tests
        shell: bash
