name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ATLAS_TOKEN: ${{ secrets.TERRAFORM_ENTERPRISE_ATLAS_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pre-commit/action@v2.0.0
      - uses: wagoid/commitlint-github-action@v2
